server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gith?useSSL=false&serverTimezone=UTC
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379


logging:
  level:
    root: info
