server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/train_ticket?useSSL=false&serverTimezone=UTC/gith
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: localhost
    port: 6379

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.demo12306.back.entity

logging:
  level:
    com.demo12306: DEBUG
