name: Java CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: rootpassword
          MYSQL_DATABASE: gith
          MYSQL_USER: user
          MYSQL_PASSWORD: password
        ports:
          - 3306:3306

      redis:
        image: redis:latest
        ports:
          - 6379:6379

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '17'
        architecture: 'x64'

    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Wait for MySQL to be ready
      run: |
        for i in {1..30}; do
          mysql -h 127.0.0.1 -u root -prootpassword -e "SELECT 1;" && break || sleep 1
        done

    - name: Grant privileges to user
      run: |
        mysql -h 127.0.0.1 -u root -prootpassword -e "GRANT ALL PRIVILEGES ON *.* TO 'user'@'%' WITH GRANT OPTION; FLUSH PRIVILEGES;"

    - name: Install dependencies
      run: mvn install -DskipTests

    - name: Import database files
      run: |
        for file in src/main/resources/db/gith/*.sql; do
          echo "Importing $file"
          mysql -h 127.0.0.1 -u user -ppassword gith < "$file" || exit 1
        done

    - name: Run unit tests
      run: mvn test -Dspring.profiles.active=dev

    - name: Run integration tests
      run: mvn verify -P integration-test
