name: Java CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: rootpassword
          MYSQL_DATABASE: train_ticket
          MYSQL_USER: user
          MYSQL_PASSWORD: password
        ports:
          - 3306:3306

      redis:
        image: redis:latest
        ports:
          - 6379:6379

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '17'
        architecture: 'x64'

    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Install dependencies
      run: mvn install -DskipTests

    - name: Import database files
      run: |
        for file in src/main/resources/db/gith/*.sql; do
          mysql -h 127.0.0.1 -P 3306 -u user -ppassword train_ticket < "$file"
        done

    - name: Run unit tests
      run: mvn test

    - name: Run integration tests
      run: mvn verify -P integration-test
